# Message for when you score a hole
scoreMsg: '&4&v1 &6completed hole &v2 in &c&v3&6 strokes.'
# Friction is like a velocity multiplier, so lower friction is "stronger" friction. Don't put something >= 1 or the ball will never stop
friction: 0.975
sand_friction: 0.9
# The Further a player is from the ball, the closer to the "max" power (It's like the player had more of a windup)
# A y power of like 0.25 is sufficient to go over a block
club_power:
  putter:
    min_power_sneaking: 0.05
    min_y_power_sneaking: 0.0
    max_power_sneaking: 0.2
    max_y_power_sneaking: 0.0
    min_power_standing: 0.2
    min_y_power_standing: 0.0
    max_power_standing: 0.4
    max_y_power_standing: 0.0
    min_power_crit: 0.4
    min_y_power_crit: 0.0
    max_power_crit: 0.55
    max_y_power_crit: 0.0
  wedge:
    min_power_sneaking: 0.05
    min_y_power_sneaking: 0.1
    max_power_sneaking: 0.1667
    max_y_power_sneaking: 0.2
    min_power_standing: 0.1667
    min_y_power_standing: 0.1
    max_power_standing: 0.3
    max_y_power_standing: 0.2
    min_power_crit: 0.3
    min_y_power_crit: 0.15
    max_power_crit: 0.45
    max_y_power_crit: 0.2
  iron:
    min_power_sneaking: 0.5
    min_y_power_sneaking: 0.0
    max_power_sneaking: 0.75
    max_y_power_sneaking: 0.0
    min_power_standing: 0.75
    min_y_power_standing: 0.0
    max_power_standing: 0.9
    max_y_power_standing: 0.0
    min_power_crit: 0.9
    min_y_power_crit: 0.025
    max_power_crit: 1.1
    max_y_power_crit: 0.05