name: MiniGolf
description: Play mini golf in Minecraft!
author: Chai
main: com.chai.miniGolf.Main
version: ${project.version}
api-version: 1.20

commands:
  mgcreatecourse:
    description: Create a Mini Golf course
    usage: /mgcreatecourse <course_name>
  mgedit:
    description: Edit Mini Golf courses
    usage: /mgedit <course_name:or_edit_action>
  mginfo:
    description: Mini golf plugin info
  mgplay:
    description: Play a Mini golf course
    usage: /mgplay <course_name> <optional:player_name>
  mgreload:
    description: Reload the configs

permissions:
  mgop:
    default: op
    description: Allows you to reload the config
