name: MiniGolf
description: Play mini golf in Minecraft!
author: Chai
main: com.chai.miniGolf.Main
version: ${project.version}
api-version: 1.20

commands:
  minigolf:
    description: Mini golf
    default: true
    usage: "Usage: /minigolf [info|reload]"
    aliases: [golf]

permissions:
  minigolf.reload:
    default: op
    description: Allows you to reload the config
